spring:
  profiles:
   active: dev

---
spring:
  config:
    activate:
      on-profile: dev
  jpa:
    hibernate.ddl-auto: none
    #database-platform: org.hibernate.dialect.Oracle10gDialect    
  datasource:
    hikari:
      jdbc-url: jdbc:oracle:thin:@//172.19.0.128:1521/BIRDTST
      username: morlandi
      password: Password123
      driverClassName: oracle.jdbc.OracleDriver
      minimum-idle: 5
      maximum-pool-size: 20
      idleTimeout: 30000
      maxLifetime: 2000000
      connectionTimeout: 30000
      #poolName: ""

server:
  port: 8080
  servlet.context-path: /fastpoint
logging.level:
  web: DEBUG #QUESTO POSSO ANCHE TOGLIERLO DOPO
  #org.springframework.jdbc.datasource.init.ScriptUtils: debug      
       
---



