pipeline {
	agent none
    stages {
        stage('Back-end') {
            agent {
                docker { image 'maven:3.8.3-openjdk-17' }

            }
            steps {
                sh 'mvn --version'
				sh 'mvn -U -X --file ./amedea-rest-parent  -DSERVICE_NAME=amedea-rest-day -DskipTests -Pprod clean install' 
            }
        }
        stage('Front-end') {
            agent {
                docker { image 'node:16.13.1-alpine' }
            }
            steps {
                sh 'node --version'
            }
        }
    }

}
