pipeline {
    agent {
        docker {
            image 'maven:3.8.3-openjdk-17' 
            args '-v /root/.m2:/root/.m2' 
        }
	}	
	parameters	{
		string(name: 'AMEDEA_DB_URL',
		defaultValue: 'jdbc:oracle:thin:@//172.19.0.128:1521/BIRDTST')
		string(name: 'AMEDEA_DB_PORT',
		defaultValue: '8083')
		password(name: 'AMEDEA_DB_PASSWORD',
			defaultValue: 'Password123')
    }
    stages {
	stage('Initialize') { 
            steps {
				sh 'java -version'	
				sh 'mvn -v'	
            }
        }	    
        stage('Build') { 
            steps {
                sh 'mvn -U -X --file ./amedea-rest-parent  -DSERVICE_NAME=amedea-rest-day -DskipTests -Pprod clean install' 
            }
        }
    }
}
